parserOptions:
  ecmaVersion: 2021

env:
  es6: true
  browser: true

extends:
  - airbnb
  - airbnb/hooks
  - prettier

plugins:
  - simple-import-sort

rules:
  class-methods-use-this: off
  global-require: off
  no-console: off
  no-param-reassign: off
  import/no-default-export: error
  import/prefer-default-export: off
  jsx-a11y/label-has-associated-control: off
  react/jsx-filename-extension: off
  react/jsx-props-no-spreading: off
  react/prop-types: off
  react/react-in-jsx-scope: off

overrides:
  - files:
      - ./pages/**/*.js
    rules:
      import/no-default-export: off
      import/prefer-default-export: error
